### ISSUE TITLE
On Xenial crashes

### ISSUE THREAD

**Issue by idekovets** [bhdouglass/rockwork#1]
Good day!

I have Nexus 5 with Xenial 16.04 RC (2018-W30). My Pebble (1th gen) connect normally. But when i try manage watchfaces or applications - RockWork crashes.

Best regards!

**Comment by bhdouglass** [comment]
Could you post the some logs after the crash? You can find them in `/home/phablet/.cache/upstart/`. There should be two there, one for the app and one for the daemon (just grep for files with "rockwork" in them).

**Comment by idekovets** [comment]
Here log. 
[rockworkd.log](https://github.com/bhdouglass/rockwork/files/2252197/rockworkd.log)

**Comment by idekovets** [comment]
Here log. (Mac of my Pebble changed)
[rockworkd.log](https://github.com/bhdouglass/rockwork/files/2252200/rockworkd.log)

**Comment by bhdouglass** [comment]
Could you also send the log of the app? Its something like `~/.cache/upstart/application-click-rockwork.log`. If your managing apps then it might be just the app that's crashing and not the daemon. Could also be related to the shutdown of the pebble app store.

**Comment by idekovets** [comment]
Sorry, i now away from UT. I will back later.15:57, 4 августа 2018 г., Brian Douglass <notifications@github.com>:Could you also send the log of the app? Its something like ~/.cache/upstart/application-click-rockwork.log. If your managing apps then it might be just the app that's crashing and not the daemon. Could also be related to the shutdown of the pebble app store.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by idekovets** [comment]
There is no application-click-rockwork.log

Only rockworkd.log

**Comment by bhdouglass** [comment]
Sorry the full path to the file is `/home/phablet/.cache/upstart/application-click-rockwork.mzanetti_rockwork_1.4.log`

**Comment by idekovets** [comment]
Good day!There is no file named application-click-rockwork.mzanetti_rockwork_1.4.log at these folder. :(7:11, 9 августа 2018 г., Brian Douglass <notifications@github.com>:Sorry the full path to the file is /home/phablet/.cache/upstart/application-click-rockwork.mzanetti_rockwork_1.4.log

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by bhdouglass** [comment]
Ah, it's probably been cleaned up, can you make it crash again and then check for the log?

**Comment by idekovets** [comment]
I specialy install UT to test it. Now i test AOSP. Tomorrow i try it again. P.S. I try install twice, and there no other files except rockworckd.log17:41, 9 августа 2018 г., Brian Douglass <notifications@github.com>:Ah, it's probably been cleaned up, can you make it crash again and then check for the log?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by idekovets** [comment]
Maybe these help: http://rebble.io/

**Comment by bhdouglass** [comment]
Yeah I've been working to convert to appstore code to use rebble, should be available soon. Could possibly fix your issue.

**Comment by idekovets** [comment]
OK1:05, 10 августа 2018 г., Brian Douglass <notifications@github.com>:Yeah I've been working to convert to appstore code to use rebble, skills be available soon. Could possibly fix your issue.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by idekovets** [comment]
Solved! With new version (v1.5) work well! Thanks!

**Comment by bhdouglass** [comment]
Awesome! I'm glad that works for you.
