### ISSUE TITLE
Version 1.5 (Vivid) on Hammerhead - crashes immediately attempting to download any app or watchface

### ISSUE THREAD

**Issue by artistechnic** [bhdouglass/rockwork#2]
RockWork 1.5 running on Nexus 5 crashes immediately when I attempt to download any app or watchface. I noticed that the log states it is for version 1.3, so I reinstalled  to be sure, but experienced the same result. I hope the attached logs will help.

[rockworkd.log](https://github.com/bhdouglass/rockwork/files/2319248/rockworkd.log)

[application-click-rockwork.mzanetti_rockwork_1.3.log](https://github.com/bhdouglass/rockwork/files/2319251/application-click-rockwork.mzanetti_rockwork_1.3.log)

**Comment by bhdouglass** [comment]
v1.5 is the current xenial version, the vivid version hasn't been updated yet. You're experiencing the crash because the pebble store shutdown. Do you have plans to upgrade to xenial (OTA 4 comes out very soon)?

**Comment by artistechnic** [comment]
Oops! I missed that 1.5 was xenial only. Guess I didn't dig deep enough before bothering you. I'll have to upgrade on OTA 4.

In the meantime, I'll have to try to figure out why I can't download from the Rebble store through the browser, but that's not your issue.

Thanks!

**Comment by bhdouglass** [comment]
No worries, it wasn't very obvious that was the case. Let me know if you have any problems with v1.5 on xenial!

You could post an issue over on the rebble store github page about downloading apps: https://github.com/pebble-dev/rebble-store
