### ISSUE TITLE
Rockwork stuck on "Loading" after Xenial update (Ver13 aka 2018-W39)

### ISSUE THREAD

**Issue by Scott-Marley** [bhdouglass/rockwork#3]
Hi, 

I'm on a Fairphone 2 and just updated the ubports Ubuntu Xenial OS to "Version 13," aka 16.04 (2018-W39). My Pebble Time Steel has lost the connection to my phone and when I load Rockwork it won't get past the "Loading" screen

Hope it's an easy fix

**Comment by bhdouglass** [comment]
What version of rock work are you running?

**Comment by Scott-Marley** [comment]
Rockwork Ver 1.5

**Comment by bhdouglass** [comment]
Can you send me the two log files:
/home/phablet/.cache/upstart/application-click-rockwork.mzanetti_rockwork_1.5.log
/home/phablet/.cache/upstart/rockworkd.log

**Comment by Scott-Marley** [comment]
Looks like this could be the problem:
`Could not connect to rockworkd.
qml: Page_QMLTYPE_19(0x304f90)"RockWork": In Ubuntu.Components 1.3, the use of Page.title, Page.flickable and Page.head is deprecated. Use Page.header and the PageHeader component instead.`
Or this:
`Could not connect to rockworkd.
qml: Service file version ( 1.5 ) is not equal running service version (  ). Restarting service.
`

[rockworkd.log](https://github.com/bhdouglass/rockwork/files/2443837/rockworkd.log)
[application-click-rockwork.mzanetti_rockwork_1.5.log](https://github.com/bhdouglass/rockwork/files/2443838/application-click-rockwork.mzanetti_rockwork_1.5.log)

**Comment by bhdouglass** [comment]
Are you running stable or another channel of 16.04? It looks like the daemon is crashing because of a weird symbol error.

**Comment by Scott-Marley** [comment]
Ah! I hadn't realised I was still on the RC channel. I'm very pleased and surprised how easy it was to roll it back to the latest stable channel image and now Rockwork is working perfectly. Thanks.

**Comment by bhdouglass** [comment]
You're welcome! It sounds like I might need to release an update for the next ota
